name: Prod_Push - Publish to Nuget

on:
  push:
    branches: master

env:
  BUILD_CONFIGURATION: 'Release'
  VERSION_MAJOR: '0'
  VERSION_MINOR: '0'
  VERSION_PATCH: '9'

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install Depedencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore     

    - name: Run Unit Tests
      run: dotnet test bleak.Slack.Tests/bleak.Slack.Tests.csproj

    - name: Publish bleak.Slack
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: bleak.Slack/bleak.Slack.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        VERSION_STATIC: ${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}.${{ env.VERSION_PATCH }}